-- Phase 5A-5C: parish Gold formula contract and read-only candidate layer.
-- This migration deliberately does not load either parish Gold fact table.

ALTER TABLE shared_analytics.dim_institutions
  DROP CONSTRAINT IF EXISTS dim_institutions_institution_id_fkey;

ALTER TABLE parish_analytics.dim_iafr_account
  DROP CONSTRAINT IF EXISTS dim_iafr_account_source_account_title_id_fkey;

ALTER TABLE parish_analytics.fact_parish_monthly_financials
  ADD COLUMN IF NOT EXISTS expenses_parish_salaries_wages_benefits numeric(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS expenses_parish_government_contributions numeric(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS expenses_parish_utilities numeric(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS expenses_parish_communications numeric(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS expenses_parish_other_rectory numeric(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE parish_analytics.fact_parish_monthly_financials
  ALTER COLUMN remittances_total DROP NOT NULL,
  ALTER COLUMN remittances_total DROP DEFAULT;

CREATE TABLE IF NOT EXISTS parish_silver.financial_memo_metrics (
  source_record_id uuid NOT NULL
    REFERENCES parish_silver.financial_records(source_record_id) ON DELETE CASCADE,
  metric_name text NOT NULL,
  metric_value numeric(14, 6) NOT NULL,
  resolution_method text NOT NULL CHECK (resolution_method IN ('source_json', 'approved_fallback')),
  source_json_key text,
  source_push_row_id uuid,
  source_push_batch_id uuid,
  source_updated_at timestamptz,
  extracted_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (source_record_id, metric_name)
);

CREATE INDEX IF NOT EXISTS idx_financial_memo_metrics_name
  ON parish_silver.financial_memo_metrics (metric_name, resolution_method);

CREATE TABLE IF NOT EXISTS warehouse_control.parish_metric_account_rules (
  rule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  formula_version text NOT NULL,
  metric_name text NOT NULL,
  effective_start_year smallint NOT NULL,
  effective_end_year smallint NOT NULL,
  account_code text,
  account_code_regex text,
  rule_role text NOT NULL DEFAULT 'include'
    CHECK (rule_role IN ('include', 'primary', 'fallback')),
  multiplier numeric(14, 6) NOT NULL DEFAULT 1,
  allocation_priority smallint NOT NULL DEFAULT 100,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (effective_start_year <= effective_end_year),
  CHECK ((account_code IS NOT NULL)::integer + (account_code_regex IS NOT NULL)::integer = 1)
);

CREATE INDEX IF NOT EXISTS idx_parish_metric_rules_lookup
  ON warehouse_control.parish_metric_account_rules
    (formula_version, effective_start_year, effective_end_year, metric_name);

DELETE FROM warehouse_control.parish_metric_account_rules
WHERE formula_version = 'parish_monthly_v1';

INSERT INTO warehouse_control.parish_metric_account_rules (
  formula_version, metric_name, effective_start_year, effective_end_year,
  account_code, account_code_regex, rule_role, multiplier, allocation_priority, notes
)
VALUES
  ('parish_monthly_v1', 'sacraments_prescribed', 2021, 2025, NULL, '^A\.1\..+\.01$', 'include', 1, 10, 'Prescribed sacrament leaf accounts'),
  ('parish_monthly_v1', 'sacraments_prescribed', 2021, 2025, 'A.2.01.01', NULL, 'include', 1, 10, 'Prescribed confirmation'),
  ('parish_monthly_v1', 'sacraments_over_above', 2021, 2025, NULL, '^A\.1\..+\.02$', 'primary', 1, 10, 'Over/above sacrament leaf accounts'),
  ('parish_monthly_v1', 'sacraments_over_above', 2021, 2025, 'A.2.01.02', NULL, 'primary', 1, 10, 'Over/above confirmation'),
  ('parish_monthly_v1', 'sacraments_over_above', 2021, 2025, 'A.1.11', NULL, 'fallback', 1, 90, 'Aggregate over/above fallback'),

  ('parish_monthly_v1', 'collections_mass', 2021, 2021, 'B.1.01', NULL, 'include', 1, 10, 'Weekday collection'),
  ('parish_monthly_v1', 'collections_mass', 2021, 2021, 'B.1.02', NULL, 'include', 1, 10, 'Sunday collection'),
  ('parish_monthly_v1', 'collections_mass', 2021, 2021, 'B.1.05', NULL, 'include', 1, 10, 'Weekday envelopes'),
  ('parish_monthly_v1', 'collections_mass', 2021, 2021, 'B.1.06', NULL, 'include', 1, 10, 'Sunday envelopes'),
  ('parish_monthly_v1', 'collections_mass', 2021, 2021, 'B.2.01', NULL, 'include', 1, 10, 'Rentals'),
  ('parish_monthly_v1', 'collections_mass', 2021, 2021, 'B.2.02', NULL, 'include', 1, 10, 'Mortuary/columbary'),
  ('parish_monthly_v1', 'collections_mass', 2021, 2021, 'B.2.04', NULL, 'include', 1, 10, 'Donation boxes'),
  ('parish_monthly_v1', 'collections_mass', 2021, 2021, 'B.2.06', NULL, 'include', 1, 10, 'Other sources'),
  ('parish_monthly_v1', 'collections_mass', 2021, 2021, 'B.3.04', NULL, 'include', 1, 10, 'Special collections'),
  ('parish_monthly_v1', 'collections_mass', 2021, 2021, 'B.3.05', NULL, 'include', 1, 10, 'Second collections'),

  ('parish_monthly_v1', 'collections_mass', 2022, 2022, 'B.1.01', NULL, 'include', 1, 10, 'Weekday collection'),
  ('parish_monthly_v1', 'collections_mass', 2022, 2022, 'B.1.02', NULL, 'include', 1, 10, 'Sunday collection'),
  ('parish_monthly_v1', 'collections_mass', 2022, 2022, 'B.1.03', NULL, 'include', 1, 10, 'Saturday anticipated collection'),
  ('parish_monthly_v1', 'collections_mass', 2022, 2022, 'B.2.01', NULL, 'include', 1, 10, 'Rentals'),
  ('parish_monthly_v1', 'collections_mass', 2022, 2022, 'B.2.02', NULL, 'include', 1, 10, 'Mortuary/columbary'),
  ('parish_monthly_v1', 'collections_mass', 2022, 2022, 'B.2.03', NULL, 'include', 1, 10, 'Kandilaan'),
  ('parish_monthly_v1', 'collections_mass', 2022, 2022, 'B.2.04', NULL, 'include', 1, 10, 'Donation boxes'),
  ('parish_monthly_v1', 'collections_mass', 2022, 2022, 'B.2.05', NULL, 'include', 1, 10, 'Envelopes'),
  ('parish_monthly_v1', 'collections_mass', 2022, 2022, 'B.2.06', NULL, 'include', 1, 10, 'Other sources'),

  ('parish_monthly_v1', 'collections_mass', 2023, 2023, 'B.1.01', NULL, 'include', 1, 10, 'Weekday collection'),
  ('parish_monthly_v1', 'collections_mass', 2023, 2023, 'B.1.02', NULL, 'include', 1, 10, 'Sunday collection'),
  ('parish_monthly_v1', 'collections_mass', 2023, 2023, 'B.1.03', NULL, 'include', 1, 10, 'Saturday anticipated collection'),
  ('parish_monthly_v1', 'collections_mass', 2023, 2023, 'B.2.05', NULL, 'include', 1, 10, 'Envelopes'),

  ('parish_monthly_v1', 'collections_mass', 2024, 2025, 'B.1.01', NULL, 'include', 1, 10, 'Weekday collection'),
  ('parish_monthly_v1', 'collections_mass', 2024, 2025, 'B.1.02', NULL, 'include', 1, 10, 'Sunday collection'),
  ('parish_monthly_v1', 'collections_mass', 2024, 2025, 'B.1.03', NULL, 'include', 1, 10, 'Saturday anticipated collection'),

  ('parish_monthly_v1', 'collections_other_95', 2021, 2021, 'B.2.03', NULL, 'include', 0.95, 20, 'Kandilaan not allocated to Mass'),
  ('parish_monthly_v1', 'collections_other_95', 2021, 2021, 'B.2.05', NULL, 'include', 0.95, 20, 'Standalone envelopes not allocated to Mass'),
  ('parish_monthly_v1', 'collections_other_95', 2021, 2021, 'B.2.07', NULL, 'include', 0.95, 20, 'Parking receipts'),
  ('parish_monthly_v1', 'collections_other_95', 2022, 2022, 'B.2.07', NULL, 'include', 0.95, 20, 'Parking receipts'),
  ('parish_monthly_v1', 'collections_other_95', 2023, 2023, 'B.2.01', NULL, 'include', 0.95, 20, 'Rentals'),
  ('parish_monthly_v1', 'collections_other_95', 2023, 2023, 'B.2.02', NULL, 'include', 0.95, 20, 'Mortuary/columbary'),
  ('parish_monthly_v1', 'collections_other_95', 2023, 2023, 'B.2.03', NULL, 'include', 0.95, 20, 'Kandilaan'),
  ('parish_monthly_v1', 'collections_other_95', 2023, 2023, 'B.2.04', NULL, 'include', 0.95, 20, 'Donation boxes'),
  ('parish_monthly_v1', 'collections_other_95', 2023, 2023, 'B.2.06', NULL, 'include', 0.95, 20, 'Other sources'),
  ('parish_monthly_v1', 'collections_other_95', 2023, 2023, 'B.2.07', NULL, 'include', 0.95, 20, 'Parking receipts'),
  ('parish_monthly_v1', 'collections_other_95', 2024, 2025, NULL, '^B\.2\.', 'include', 0.95, 20, 'All Other Collections'),

  ('parish_monthly_v1', 'collections_other_receipts', 2021, 2021, 'B.3.01', NULL, 'include', 1, 30, 'Donations'),
  ('parish_monthly_v1', 'collections_other_receipts', 2021, 2021, 'B.3.02', NULL, 'include', 1, 30, 'Interest income'),
  ('parish_monthly_v1', 'collections_other_receipts', 2021, 2021, 'B.3.03', NULL, 'include', 1, 30, 'Subsidy'),
  ('parish_monthly_v1', 'collections_other_receipts', 2021, 2021, 'B.3.07', NULL, 'include', 1, 30, 'Other receipts'),
  ('parish_monthly_v1', 'collections_other_receipts', 2022, 2025, 'B.3.01', NULL, 'include', 1, 30, 'Donations'),
  ('parish_monthly_v1', 'collections_other_receipts', 2022, 2025, 'B.3.02', NULL, 'include', 1, 30, 'Interest income'),
  ('parish_monthly_v1', 'collections_other_receipts', 2022, 2025, 'B.3.03', NULL, 'include', 1, 30, 'Subsidy'),
  ('parish_monthly_v1', 'collections_other_receipts', 2022, 2025, 'B.3.04', NULL, 'include', 1, 30, 'Special collections'),
  ('parish_monthly_v1', 'collections_other_receipts', 2022, 2025, 'B.3.05', NULL, 'include', 1, 30, 'Second collections'),
  ('parish_monthly_v1', 'collections_other_receipts', 2022, 2025, 'B.3.07', NULL, 'include', 1, 30, 'Other receipts'),

  ('parish_monthly_v1', 'expenses_pastoral_mass_stipend', 2021, 2025, 'C.1.04', NULL, 'include', 1, 10, 'Confirmation Minister - Priest'),
  ('parish_monthly_v1', 'expenses_pastoral_mass_stipend', 2021, 2025, 'C.1.05', NULL, 'include', 1, 10, 'Others - Priest Share'),
  ('parish_monthly_v1', 'expenses_pastoral_mass_stipend', 2021, 2021, 'C.2.04', NULL, 'include', 1, 10, 'Combined parish and guest stipend'),
  ('parish_monthly_v1', 'expenses_pastoral_mass_stipend', 2022, 2025, 'C.2.01', NULL, 'include', 1, 10, 'Parish Priest stipend/share'),
  ('parish_monthly_v1', 'expenses_pastoral_mass_stipend', 2022, 2025, 'C.2.02', NULL, 'include', 1, 10, 'Parochial Vicar stipend'),
  ('parish_monthly_v1', 'expenses_pastoral_mass_stipend', 2022, 2025, 'C.2.03', NULL, 'include', 1, 10, 'Guest Priest stipend'),
  ('parish_monthly_v1', 'expenses_pastoral_mass_stipend', 2021, 2025, 'C.3.01', NULL, 'include', 1, 10, 'Confirmation Minister - Others'),

  ('parish_monthly_v1', 'expenses_parish_salaries_wages_benefits', 2021, 2025, NULL, '^D\.1\.', 'include', 1, 10, 'Section D.1'),
  ('parish_monthly_v1', 'expenses_parish_government_contributions', 2021, 2025, NULL, '^D\.2\.', 'include', 1, 10, 'Section D.2'),
  ('parish_monthly_v1', 'expenses_parish_utilities', 2021, 2025, NULL, '^D\.3\.', 'include', 1, 10, 'Section D.3'),
  ('parish_monthly_v1', 'expenses_parish_communications', 2021, 2025, NULL, '^D\.4\.', 'include', 1, 10, 'Section D.4'),
  ('parish_monthly_v1', 'expenses_parish_other_rectory', 2021, 2025, NULL, '^D\.5\.', 'include', 1, 10, 'Section D.5'),

  ('parish_monthly_v1', 'mass_intentions_unclaimed', 2021, 2025, 'A.3.03', NULL, 'primary', 1, 10, 'Not claimed by Parish Priest'),
  ('parish_monthly_v1', 'mass_intentions_unclaimed', 2021, 2025, 'A.3.01', NULL, 'fallback', 1, 90, 'Historical fallback'),
  ('parish_monthly_v1', 'mass_intentions_claimed', 2021, 2025, 'A.3.02', NULL, 'include', 1, 10, 'Claimed by Parish Priest'),
  ('parish_monthly_v1', 'special_collections', 2021, 2025, 'B.3.04', NULL, 'include', 1, 10, 'Receipt-side special collections'),
  ('parish_monthly_v1', 'special_collections', 2021, 2025, 'F.3.01', NULL, 'include', 1, 10, 'Remittance-side special collections');

CREATE OR REPLACE VIEW parish_analytics.vw_parish_monthly_financial_candidates AS
WITH mapped_lines AS (
  SELECT
    l.source_record_id,
    rules.metric_name,
    rules.rule_role,
    SUM(l.amount * rules.multiplier)::numeric(18, 2) AS amount
  FROM parish_silver.financial_line_items l
  JOIN parish_silver.financial_records fr
    ON fr.source_record_id = l.source_record_id
  JOIN warehouse_control.parish_metric_account_rules rules
    ON rules.formula_version = 'parish_monthly_v1'
   AND fr.reporting_year BETWEEN rules.effective_start_year AND rules.effective_end_year
   AND (
     rules.account_code = l.account_code
     OR (rules.account_code_regex IS NOT NULL AND l.account_code ~ rules.account_code_regex)
   )
  GROUP BY l.source_record_id, rules.metric_name, rules.rule_role
),
pivoted AS (
  SELECT
    source_record_id,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'sacraments_prescribed'), 0) AS sacraments_prescribed,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'sacraments_over_above' AND rule_role = 'primary'), 0) AS over_above_primary,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'sacraments_over_above' AND rule_role = 'fallback'), 0) AS over_above_fallback,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'collections_mass'), 0) AS collections_mass,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'collections_other_95'), 0) AS collections_other_95,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'collections_other_receipts'), 0) AS collections_other_receipts,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'expenses_pastoral_mass_stipend'), 0) AS expenses_pastoral_mass_stipend,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'expenses_parish_salaries_wages_benefits'), 0) AS expenses_parish_salaries_wages_benefits,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'expenses_parish_government_contributions'), 0) AS expenses_parish_government_contributions,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'expenses_parish_utilities'), 0) AS expenses_parish_utilities,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'expenses_parish_communications'), 0) AS expenses_parish_communications,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'expenses_parish_other_rectory'), 0) AS expenses_parish_other_rectory,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'mass_intentions_unclaimed' AND rule_role = 'primary'), 0) AS unclaimed_primary,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'mass_intentions_unclaimed' AND rule_role = 'fallback'), 0) AS unclaimed_fallback,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'mass_intentions_claimed'), 0) AS mass_intentions_claimed,
    COALESCE(SUM(amount) FILTER (WHERE metric_name = 'special_collections'), 0) AS special_collections
  FROM mapped_lines
  GROUP BY source_record_id
),
components AS (
  SELECT
    fr.source_record_id,
    fr.institution_id,
    fr.reporting_month,
    fr.reporting_year,
    fr.reporting_month_number,
    dp.parish_key,
    (fr.reporting_year * 100 + fr.reporting_month_number)::integer AS date_key,
    ds.submission_key,
    'parish_monthly_v1'::text AS formula_version,
    COALESCE(mm.metric_value, 0.30)::numeric(14, 6) AS parish_share_rate,
    COALESCE(mm.resolution_method, 'approved_fallback')::text AS rate_resolution_method,
    COALESCE(p.sacraments_prescribed, 0)::numeric(14, 2) AS sacraments_arancel_confirmation_incl,
    (COALESCE(p.sacraments_prescribed, 0) * COALESCE(mm.metric_value, 0.30))::numeric(14, 2) AS sacraments_parish_share,
    CASE
      WHEN COALESCE(p.over_above_primary, 0) <> 0 THEN p.over_above_primary
      ELSE COALESCE(p.over_above_fallback, 0)
    END::numeric(14, 2) AS sacraments_over_above_confirmation_incl,
    COALESCE(p.collections_mass, 0)::numeric(14, 2) AS collections_mass,
    COALESCE(p.collections_other_95, 0)::numeric(14, 2) AS collections_other_95,
    COALESCE(p.collections_other_receipts, 0)::numeric(14, 2) AS collections_other_receipts,
    COALESCE(p.expenses_pastoral_mass_stipend, 0)::numeric(14, 2) AS expenses_pastoral_mass_stipend,
    COALESCE(p.expenses_parish_salaries_wages_benefits, 0)::numeric(14, 2) AS expenses_parish_salaries_wages_benefits,
    COALESCE(p.expenses_parish_government_contributions, 0)::numeric(14, 2) AS expenses_parish_government_contributions,
    COALESCE(p.expenses_parish_utilities, 0)::numeric(14, 2) AS expenses_parish_utilities,
    COALESCE(p.expenses_parish_communications, 0)::numeric(14, 2) AS expenses_parish_communications,
    COALESCE(p.expenses_parish_other_rectory, 0)::numeric(14, 2) AS expenses_parish_other_rectory,
    CASE
      WHEN COALESCE(p.unclaimed_primary, 0) <> 0 THEN p.unclaimed_primary
      ELSE COALESCE(p.unclaimed_fallback, 0)
    END::numeric(14, 2) AS mass_intentions_not_claimed_by_parish_priest,
    COALESCE(p.mass_intentions_claimed, 0)::numeric(14, 2) AS mass_intentions_claimed_by_parish_priest,
    COALESCE(p.special_collections, 0)::numeric(14, 2) AS special_collections,
    fr.quality_status AS silver_quality_status,
    fr.quality_flags AS silver_quality_flags
  FROM parish_silver.financial_records fr
  LEFT JOIN pivoted p ON p.source_record_id = fr.source_record_id
  LEFT JOIN parish_silver.financial_memo_metrics mm
    ON mm.source_record_id = fr.source_record_id
   AND mm.metric_name = 'sacraments_parish_share_rate'
  LEFT JOIN shared_analytics.dim_institutions di ON di.institution_id = fr.institution_id
  LEFT JOIN parish_analytics.dim_parishes dp ON dp.institution_key = di.institution_key
  LEFT JOIN shared_analytics.dim_submission ds ON ds.financial_record_id = fr.source_record_id
),
expense_totals AS (
  SELECT
    c.*,
    (
      c.expenses_parish_salaries_wages_benefits
      + c.expenses_parish_government_contributions
      + c.expenses_parish_utilities
      + c.expenses_parish_communications
      + c.expenses_parish_other_rectory
    )::numeric(14, 2) AS expenses_parish
  FROM components c
),
collection_and_expense_totals AS (
  SELECT
    e.*,
    (
      e.sacraments_parish_share
      + e.sacraments_over_above_confirmation_incl
      + e.collections_mass
      + e.collections_other_95
      + e.collections_other_receipts
    )::numeric(14, 2) AS total_collections,
    (e.expenses_pastoral_mass_stipend + e.expenses_parish)::numeric(14, 2) AS total_expenses
  FROM expense_totals e
),
net_totals AS (
  SELECT
    t.*,
    (t.total_collections - t.total_expenses)::numeric(14, 2) AS net_receipts_deficit
  FROM collection_and_expense_totals t
)
SELECT
  n.*,
  (
    n.net_receipts_deficit
    + n.mass_intentions_not_claimed_by_parish_priest
    - n.special_collections
  )::numeric(14, 2) AS pastoral_parish_fund_total_net_receipts_deficit,
  NULL::numeric(14, 2) AS remittances_total,
  CASE
    WHEN n.parish_key IS NULL THEN 'failed'
    WHEN n.rate_resolution_method = 'approved_fallback' THEN 'warning'
    ELSE 'passed'
  END::text AS calculation_status
FROM net_totals n;

COMMENT ON VIEW parish_analytics.vw_parish_monthly_financial_candidates IS
  'Read-only Phase 5 candidate calculations; does not populate parish Gold facts.';
