-- Rebuildable school/seminary Silver layers. Operational source UUIDs remain
-- lineage values; every enforced relationship stays inside AWS analytics.

CREATE SCHEMA IF NOT EXISTS school_silver;
CREATE SCHEMA IF NOT EXISTS seminary_silver;

CREATE TABLE IF NOT EXISTS school_silver.financial_records (
  record_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_record_id uuid NOT NULL UNIQUE,
  institution_key integer NOT NULL
    REFERENCES shared_analytics.dim_institutions(institution_key),
  source_institution_id uuid NOT NULL,
  source_submission_batch_id uuid,
  reporting_year smallint NOT NULL,
  reporting_month smallint NOT NULL CHECK (reporting_month BETWEEN 1 AND 12),
  source_status text,
  source_version_no integer,
  is_current_version boolean NOT NULL DEFAULT true,
  financial_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_updated_at timestamptz,
  source_deleted_at timestamptz,
  warehouse_updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS school_silver.financial_line_items (
  line_item_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_line_item_id uuid NOT NULL UNIQUE,
  record_key bigint NOT NULL
    REFERENCES school_silver.financial_records(record_key) ON DELETE CASCADE,
  source_account_title_id uuid,
  section_code text,
  subsection_code text,
  item_code text,
  item_label text NOT NULL,
  item_type text,
  amount numeric(14,2) NOT NULL DEFAULT 0,
  source_updated_at timestamptz,
  source_deleted_at timestamptz,
  warehouse_updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_school_silver_records_institution_period
  ON school_silver.financial_records(institution_key, reporting_year, reporting_month);
CREATE INDEX IF NOT EXISTS idx_school_silver_lines_record
  ON school_silver.financial_line_items(record_key);

CREATE TABLE IF NOT EXISTS seminary_silver.financial_records (
  record_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_record_id uuid NOT NULL UNIQUE,
  institution_key integer NOT NULL
    REFERENCES shared_analytics.dim_institutions(institution_key),
  source_institution_id uuid NOT NULL,
  source_submission_batch_id uuid,
  reporting_year smallint NOT NULL,
  reporting_month smallint NOT NULL CHECK (reporting_month BETWEEN 1 AND 12),
  source_status text,
  source_version_no integer,
  is_current_version boolean NOT NULL DEFAULT true,
  financial_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_updated_at timestamptz,
  source_deleted_at timestamptz,
  warehouse_updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS seminary_silver.financial_line_items (
  line_item_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_line_item_id uuid NOT NULL UNIQUE,
  record_key bigint NOT NULL
    REFERENCES seminary_silver.financial_records(record_key) ON DELETE CASCADE,
  source_account_title_id uuid,
  section_code text,
  subsection_code text,
  item_code text,
  item_label text NOT NULL,
  item_type text,
  amount numeric(14,2) NOT NULL DEFAULT 0,
  source_updated_at timestamptz,
  source_deleted_at timestamptz,
  warehouse_updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_seminary_silver_records_institution_period
  ON seminary_silver.financial_records(institution_key, reporting_year, reporting_month);
CREATE INDEX IF NOT EXISTS idx_seminary_silver_lines_record
  ON seminary_silver.financial_line_items(record_key);

