CREATE TABLE IF NOT EXISTS shared_analytics.dim_institutions (
  institution_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution_id uuid NOT NULL UNIQUE REFERENCES diocese.institutions(id),
  institution_name text NOT NULL,
  institution_type text NOT NULL CHECK (institution_type IN ('parish', 'school', 'seminary')),
  vicariate text,
  district  text,
  cluster   text,
  class     text CHECK (class IN ('A', 'B', 'C', 'D', 'E') OR class IS NULL)
);

CREATE TABLE IF NOT EXISTS shared_analytics.dim_date (
  date_key integer PRIMARY KEY,
  month_name text NOT NULL,
  month_number smallint NOT NULL CHECK (month_number BETWEEN 1 AND 12),
  month_short text NOT NULL,
  year smallint NOT NULL,
  quarter text NOT NULL,
  academic_year_period boolean NOT NULL DEFAULT false,
  is_fiesta_season boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS shared_analytics.dim_submission (
  submission_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_batch_id uuid UNIQUE REFERENCES operations.submission_batches(id),
  financial_record_id uuid,
  source_file_name text,
  submitted_by uuid REFERENCES diocese.profiles(id),
  submitted_at timestamptz,
  verified_by uuid REFERENCES diocese.profiles(id),
  verified_at timestamptz,
  status text,
  version_no integer,
  is_current_version boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS shared_analytics.model_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_name text NOT NULL,
  model_version text,
  model_type text NOT NULL CHECK (model_type IN ('forecast', 'anomaly', 'health_score', 'assignment_recommendation', 'optimization')),
  input_start_date date,
  input_end_date date,
  run_status text NOT NULL CHECK (run_status IN ('pending', 'running', 'succeeded', 'failed')),
  metrics jsonb,
  started_at timestamptz,
  finished_at timestamptz,
  created_by uuid REFERENCES diocese.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS shared_analytics.fact_subsidy_allocations (
  allocation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_key integer NOT NULL REFERENCES shared_analytics.dim_institutions(institution_key),
  model_run_id uuid NOT NULL REFERENCES shared_analytics.model_runs(id),
  annual_deficit numeric(14, 2) NOT NULL DEFAULT 0,
  recommended_subsidy numeric(14, 2) NOT NULL DEFAULT 0,
  allocated_subsidy numeric(14, 2) NOT NULL DEFAULT 0,
  run_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dim_institutions_entity_type
  ON shared_analytics.dim_institutions (institution_type);

CREATE INDEX IF NOT EXISTS idx_model_runs_type_status
  ON shared_analytics.model_runs (model_type, run_status);

DROP TRIGGER IF EXISTS set_updated_at_model_runs ON shared_analytics.model_runs;
CREATE TRIGGER set_updated_at_model_runs
BEFORE UPDATE ON shared_analytics.model_runs
FOR EACH ROW EXECUTE FUNCTION public.set_row_updated_at();
