CREATE TABLE IF NOT EXISTS parish_analytics.dim_parishes (
  parish_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution_key integer NOT NULL UNIQUE REFERENCES shared_analytics.dim_institutions(institution_key),
  vicariate text,
  district text,
  cluster text,
  assigned_priest text,
  address text,
  latitude numeric(10, 7),
  longitude numeric(10, 7)
);

CREATE TABLE IF NOT EXISTS parish_analytics.dim_iafr_account (
  iafr_account_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_account_title_id uuid UNIQUE REFERENCES parishes.iafr_account_titles(id),
  section_code text NOT NULL,
  subsection_code text,
  account_code text NOT NULL UNIQUE,
  account_name text NOT NULL,
  account_type text NOT NULL,
  classification text,
  is_arancel_related boolean NOT NULL DEFAULT false,
  is_mass_collection boolean NOT NULL DEFAULT false,
  is_remittable boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS parish_analytics.fact_parish_monthly_financials (
  parish_key integer NOT NULL REFERENCES parish_analytics.dim_parishes(parish_key),
  date_key integer NOT NULL REFERENCES shared_analytics.dim_date(date_key),
  submission_key integer REFERENCES shared_analytics.dim_submission(submission_key),
  sacraments_arancel_confirmation_incl numeric(14, 2) NOT NULL DEFAULT 0,
  sacraments_parish_share numeric(14, 2) NOT NULL DEFAULT 0,
  sacraments_over_above_confirmation_incl numeric(14, 2) NOT NULL DEFAULT 0,
  collections_mass numeric(14, 2) NOT NULL DEFAULT 0,
  collections_other_95 numeric(14, 2) NOT NULL DEFAULT 0,
  collections_other_receipts numeric(14, 2) NOT NULL DEFAULT 0,
  total_collections numeric(14, 2) NOT NULL DEFAULT 0,
  expenses_pastoral_mass_stipend numeric(14, 2) NOT NULL DEFAULT 0,
  expenses_parish numeric(14, 2) NOT NULL DEFAULT 0,
  total_expenses numeric(14, 2) NOT NULL DEFAULT 0,
  net_receipts_deficit numeric(14, 2) NOT NULL DEFAULT 0,
  mass_intentions_not_claimed_by_parish_priest numeric(14, 2) NOT NULL DEFAULT 0,
  mass_intentions_claimed_by_parish_priest numeric(14, 2) NOT NULL DEFAULT 0,
  special_collections numeric(14, 2) NOT NULL DEFAULT 0,
  pastoral_parish_fund_total_net_receipts_deficit numeric(14, 2) NOT NULL DEFAULT 0,
  typhoon_days_count smallint NOT NULL DEFAULT 0,
  major_events_count smallint NOT NULL DEFAULT 0,
  minor_events_count smallint NOT NULL DEFAULT 0,
  has_event boolean NOT NULL DEFAULT false,
  total_rainfall_mm numeric(14, 2) NOT NULL DEFAULT 0,
  PRIMARY KEY (parish_key, date_key)
);

CREATE TABLE IF NOT EXISTS parish_analytics.fact_parish_financial_breakdowns (
  parish_key integer NOT NULL REFERENCES parish_analytics.dim_parishes(parish_key),
  date_key integer NOT NULL REFERENCES shared_analytics.dim_date(date_key),
  submission_key integer REFERENCES shared_analytics.dim_submission(submission_key),
  iafr_account_key integer NOT NULL REFERENCES parish_analytics.dim_iafr_account(iafr_account_key),
  amount numeric(14, 2) NOT NULL DEFAULT 0,
  PRIMARY KEY (parish_key, date_key, iafr_account_key)
);

CREATE TABLE IF NOT EXISTS parish_analytics.fact_parish_financial_forecasts (
  forecast_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parish_key integer NOT NULL REFERENCES parish_analytics.dim_parishes(parish_key),
  date_key integer NOT NULL REFERENCES shared_analytics.dim_date(date_key),
  model_run_id uuid NOT NULL REFERENCES shared_analytics.model_runs(id),
  forecast_level text NOT NULL CHECK (forecast_level IN ('monthly_kpi', 'account_breakdown')),
  metric_type text NOT NULL,
  iafr_account_key integer REFERENCES parish_analytics.dim_iafr_account(iafr_account_key),
  predicted_value numeric(14, 2) NOT NULL DEFAULT 0,
  lower_confidence numeric(14, 2),
  upper_confidence numeric(14, 2)
);

CREATE TABLE IF NOT EXISTS parish_analytics.fact_parish_anomaly_alerts (
  alert_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parish_key integer NOT NULL REFERENCES parish_analytics.dim_parishes(parish_key),
  date_key integer NOT NULL REFERENCES shared_analytics.dim_date(date_key),
  iafr_account_key integer REFERENCES parish_analytics.dim_iafr_account(iafr_account_key),
  anomaly_score numeric(14, 4) NOT NULL DEFAULT 0,
  is_anomaly boolean NOT NULL DEFAULT false,
  severity_level text,
  anomaly_type text
);

CREATE TABLE IF NOT EXISTS parish_analytics.fact_parish_health_snapshots (
  snapshot_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parish_key integer NOT NULL REFERENCES parish_analytics.dim_parishes(parish_key),
  date_key integer NOT NULL REFERENCES shared_analytics.dim_date(date_key),
  composite_score numeric(5, 2) NOT NULL DEFAULT 0,
  liquidity_score numeric(5, 2) NOT NULL DEFAULT 0,
  sustainability_score numeric(5, 2) NOT NULL DEFAULT 0,
  stability_score numeric(5, 2) NOT NULL DEFAULT 0
);
