-- Historical rename migration. Both targets have been superseded:
-- parishes.details.assigned_priest was replaced by assigned_priest_id (FK) in the personnel FK fix.
-- parish_analytics.dim_parishes is created with assigned_priest in 070_parish_analytics.sql.
-- This file is intentionally a no-op and kept only for migration sequence continuity.
