CREATE TABLE IF NOT EXISTS seminary_analytics.dim_seminaries (
  seminary_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution_key integer NOT NULL UNIQUE REFERENCES shared_analytics.dim_institutions(institution_key),
  rector text,
  address text
);

CREATE TABLE IF NOT EXISTS seminary_analytics.dim_seminary_fs_account (
  seminary_account_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_account_title_id uuid UNIQUE REFERENCES seminaries.fs_account_titles(id),
  section_code text,
  subsection_code text,
  account_code text NOT NULL UNIQUE,
  account_name text NOT NULL,
  account_type text NOT NULL CHECK (account_type IN ('receipt', 'expense', 'balance', 'memo')),
  classification text
);

CREATE TABLE IF NOT EXISTS seminary_analytics.fact_seminary_monthly_financials (
  seminary_key integer NOT NULL REFERENCES seminary_analytics.dim_seminaries(seminary_key),
  date_key integer NOT NULL REFERENCES shared_analytics.dim_date(date_key),
  submission_key integer REFERENCES shared_analytics.dim_submission(submission_key),
  donations numeric(14, 2) NOT NULL DEFAULT 0,
  seminary_fees numeric(14, 2) NOT NULL DEFAULT 0,
  mass_collections numeric(14, 2) NOT NULL DEFAULT 0,
  other_sources numeric(14, 2) NOT NULL DEFAULT 0,
  subsidy_from_rbscp numeric(14, 2) NOT NULL DEFAULT 0,
  total_expenses numeric(14, 2) NOT NULL DEFAULT 0,
  net_surplus numeric(14, 2) NOT NULL DEFAULT 0,
  dependency_ratio numeric(14, 4) NOT NULL DEFAULT 0,
  typhoon_days_count smallint NOT NULL DEFAULT 0,
  has_event boolean NOT NULL DEFAULT false,
  major_events_count smallint NOT NULL DEFAULT 0,
  minor_events_count smallint NOT NULL DEFAULT 0,
  total_rainfall_mm numeric(14, 2) NOT NULL DEFAULT 0,
  PRIMARY KEY (seminary_key, date_key)
);

CREATE TABLE IF NOT EXISTS seminary_analytics.fact_seminary_financial_breakdowns (
  seminary_key integer NOT NULL REFERENCES seminary_analytics.dim_seminaries(seminary_key),
  date_key integer NOT NULL REFERENCES shared_analytics.dim_date(date_key),
  submission_key integer REFERENCES shared_analytics.dim_submission(submission_key),
  seminary_account_key integer NOT NULL REFERENCES seminary_analytics.dim_seminary_fs_account(seminary_account_key),
  amount numeric(14, 2) NOT NULL DEFAULT 0,
  PRIMARY KEY (seminary_key, date_key, seminary_account_key)
);

CREATE TABLE IF NOT EXISTS seminary_analytics.fact_seminary_financial_forecasts (
  forecast_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  seminary_key integer NOT NULL REFERENCES seminary_analytics.dim_seminaries(seminary_key),
  date_key integer NOT NULL REFERENCES shared_analytics.dim_date(date_key),
  model_run_id uuid NOT NULL REFERENCES shared_analytics.model_runs(id),
  forecast_level text NOT NULL CHECK (forecast_level IN ('monthly_kpi', 'account_breakdown')),
  metric_type text NOT NULL,
  seminary_account_key integer REFERENCES seminary_analytics.dim_seminary_fs_account(seminary_account_key),
  predicted_value numeric(14, 2) NOT NULL DEFAULT 0,
  lower_confidence numeric(14, 2),
  upper_confidence numeric(14, 2)
);

CREATE TABLE IF NOT EXISTS seminary_analytics.fact_seminary_anomaly_alerts (
  alert_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  seminary_key integer NOT NULL REFERENCES seminary_analytics.dim_seminaries(seminary_key),
  date_key integer NOT NULL REFERENCES shared_analytics.dim_date(date_key),
  seminary_account_key integer REFERENCES seminary_analytics.dim_seminary_fs_account(seminary_account_key),
  anomaly_score numeric(14, 4) NOT NULL DEFAULT 0,
  is_anomaly boolean NOT NULL DEFAULT false,
  severity_level text,
  anomaly_type text
);

CREATE TABLE IF NOT EXISTS seminary_analytics.fact_seminary_health_snapshots (
  snapshot_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  seminary_key integer NOT NULL REFERENCES seminary_analytics.dim_seminaries(seminary_key),
  date_key integer NOT NULL REFERENCES shared_analytics.dim_date(date_key),
  composite_score numeric(5, 2) NOT NULL DEFAULT 0,
  liquidity_score numeric(5, 2) NOT NULL DEFAULT 0,
  sustainability_score numeric(5, 2) NOT NULL DEFAULT 0,
  stability_score numeric(5, 2) NOT NULL DEFAULT 0
);
