CREATE TABLE IF NOT EXISTS priest_assignment_analytics.dim_priests (
  priest_key              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id              uuid NOT NULL UNIQUE REFERENCES diocese.profiles(id),
  full_name               text NOT NULL,
  email                   text,
  contact_number          text,
  is_active               boolean NOT NULL DEFAULT true,
  -- Current assignment snapshot (denormalized for analytics queries)
  current_institution_key integer REFERENCES shared_analytics.dim_institutions(institution_key),
  parish_assigned         text,
  assignment_start_date   date,
  assignment_end_date     date
);

CREATE TABLE IF NOT EXISTS priest_assignment_analytics.fact_priest_assignment_recommendations (
  recommendation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  priest_key integer NOT NULL REFERENCES priest_assignment_analytics.dim_priests(priest_key),
  institution_key integer NOT NULL REFERENCES shared_analytics.dim_institutions(institution_key),
  date_key integer NOT NULL REFERENCES shared_analytics.dim_date(date_key),
  model_run_id uuid NOT NULL REFERENCES shared_analytics.model_runs(id),
  recommended_role text,
  recommendation_type text NOT NULL CHECK (recommendation_type IN ('new_assignment', 'transfer', 'temporary_support')),
  recommendation_score numeric(14, 4) NOT NULL DEFAULT 0,
  priority_level text,
  financial_need_score numeric(14, 4) NOT NULL DEFAULT 0,
  stability_score numeric(14, 4) NOT NULL DEFAULT 0,
  forecast_risk_score numeric(14, 4) NOT NULL DEFAULT 0,
  anomaly_risk_score numeric(14, 4) NOT NULL DEFAULT 0,
  explanation jsonb,
  recommendation_status text NOT NULL CHECK (recommendation_status IN ('candidate', 'selected', 'rejected'))
);

CREATE TABLE IF NOT EXISTS priest_assignment_analytics.fact_priest_assignments (
  priest_key integer NOT NULL REFERENCES priest_assignment_analytics.dim_priests(priest_key),
  institution_key integer NOT NULL REFERENCES shared_analytics.dim_institutions(institution_key),
  start_date_key integer NOT NULL REFERENCES shared_analytics.dim_date(date_key),
  end_date_key integer REFERENCES shared_analytics.dim_date(date_key),
  assignment_role text,
  status text,
  is_active boolean NOT NULL DEFAULT true,
  PRIMARY KEY (priest_key, institution_key, start_date_key)
);
