-- Effective-dated progressive taxation schemes for parish mass collections.

BEGIN;

CREATE TABLE IF NOT EXISTS diocese.progressive_tax_schemes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version integer GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  name text NOT NULL CHECK (length(btrim(name)) > 0),
  effective_month date NOT NULL UNIQUE
    CHECK (effective_month = date_trunc('month', effective_month)::date),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  created_by uuid REFERENCES diocese.profiles(id) ON DELETE SET NULL,
  published_by uuid REFERENCES diocese.profiles(id) ON DELETE SET NULL,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (status = 'draft' AND published_at IS NULL)
    OR (status = 'published' AND published_at IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS diocese.progressive_tax_brackets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scheme_id uuid NOT NULL REFERENCES diocese.progressive_tax_schemes(id) ON DELETE CASCADE,
  position smallint NOT NULL CHECK (position > 0),
  minimum_amount numeric(14, 2) NOT NULL CHECK (minimum_amount >= 0),
  maximum_amount numeric(14, 2) NOT NULL CHECK (maximum_amount >= minimum_amount),
  rate numeric(7, 6) NOT NULL CHECK (rate > 0 AND rate <= 1),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (scheme_id, position),
  UNIQUE (scheme_id, minimum_amount),
  UNIQUE (scheme_id, maximum_amount)
);

CREATE INDEX IF NOT EXISTS idx_progressive_tax_schemes_effective
  ON diocese.progressive_tax_schemes (effective_month DESC)
  WHERE status = 'published';

CREATE INDEX IF NOT EXISTS idx_progressive_tax_brackets_scheme
  ON diocese.progressive_tax_brackets (scheme_id, position);

CREATE OR REPLACE FUNCTION diocese.guard_published_progressive_tax_scheme()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.status = 'published' THEN
    RAISE EXCEPTION 'Published progressive taxation schemes are immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION diocese.guard_published_progressive_tax_bracket()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_scheme_id uuid;
  v_status text;
BEGIN
  v_scheme_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.scheme_id ELSE NEW.scheme_id END;
  SELECT status INTO v_status
  FROM diocese.progressive_tax_schemes
  WHERE id = v_scheme_id;

  IF v_status = 'published' THEN
    RAISE EXCEPTION 'Brackets belonging to a published taxation scheme are immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS guard_published_progressive_tax_scheme
  ON diocese.progressive_tax_schemes;
CREATE TRIGGER guard_published_progressive_tax_scheme
BEFORE UPDATE OR DELETE ON diocese.progressive_tax_schemes
FOR EACH ROW EXECUTE FUNCTION diocese.guard_published_progressive_tax_scheme();

DROP TRIGGER IF EXISTS guard_published_progressive_tax_bracket
  ON diocese.progressive_tax_brackets;
CREATE TRIGGER guard_published_progressive_tax_bracket
BEFORE INSERT OR UPDATE OR DELETE ON diocese.progressive_tax_brackets
FOR EACH ROW EXECUTE FUNCTION diocese.guard_published_progressive_tax_bracket();

DROP TRIGGER IF EXISTS set_updated_at_progressive_tax_schemes
  ON diocese.progressive_tax_schemes;
CREATE TRIGGER set_updated_at_progressive_tax_schemes
BEFORE UPDATE ON diocese.progressive_tax_schemes
FOR EACH ROW EXECUTE FUNCTION public.set_row_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_progressive_tax_brackets
  ON diocese.progressive_tax_brackets;
CREATE TRIGGER set_updated_at_progressive_tax_brackets
BEFORE UPDATE ON diocese.progressive_tax_brackets
FOR EACH ROW EXECUTE FUNCTION public.set_row_updated_at();

-- Draft payloads contain only upper bounds and decimal rates. Minimums are
-- derived here to guarantee centavo-contiguous ranges.
CREATE OR REPLACE FUNCTION diocese.save_progressive_tax_draft(
  p_scheme_id uuid,
  p_name text,
  p_effective_month date,
  p_brackets jsonb,
  p_actor_id uuid
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = diocese, public
AS $$
DECLARE
  v_scheme_id uuid;
  v_item jsonb;
  v_position integer := 0;
  v_minimum numeric(14, 2) := 1.00;
  v_maximum numeric(14, 2);
  v_rate numeric(7, 6);
BEGIN
  IF p_name IS NULL OR length(btrim(p_name)) = 0 THEN
    RAISE EXCEPTION 'A taxation scheme name is required';
  END IF;
  IF p_effective_month IS NULL
     OR p_effective_month <> date_trunc('month', p_effective_month)::date THEN
    RAISE EXCEPTION 'Effective month must be the first day of a month';
  END IF;
  IF p_brackets IS NULL OR jsonb_typeof(p_brackets) <> 'array'
     OR jsonb_array_length(p_brackets) = 0 THEN
    RAISE EXCEPTION 'At least one progressive taxation bracket is required';
  END IF;

  IF p_scheme_id IS NULL THEN
    INSERT INTO diocese.progressive_tax_schemes (
      name, effective_month, status, created_by
    ) VALUES (
      btrim(p_name), p_effective_month, 'draft', p_actor_id
    )
    RETURNING id INTO v_scheme_id;
  ELSE
    SELECT id INTO v_scheme_id
    FROM diocese.progressive_tax_schemes
    WHERE id = p_scheme_id AND status = 'draft'
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Draft taxation scheme % was not found', p_scheme_id;
    END IF;

    UPDATE diocese.progressive_tax_schemes
    SET name = btrim(p_name), effective_month = p_effective_month
    WHERE id = v_scheme_id;

    DELETE FROM diocese.progressive_tax_brackets WHERE scheme_id = v_scheme_id;
  END IF;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_brackets)
  LOOP
    v_position := v_position + 1;
    BEGIN
      v_maximum := (v_item->>'maximumAmount')::numeric(14, 2);
      v_rate := (v_item->>'rate')::numeric(7, 6);
    EXCEPTION WHEN OTHERS THEN
      RAISE EXCEPTION 'Bracket % has an invalid maximum amount or rate', v_position;
    END;

    IF v_maximum IS NULL OR v_maximum < v_minimum THEN
      RAISE EXCEPTION 'Bracket % must end at or above %', v_position, v_minimum;
    END IF;
    IF v_rate IS NULL OR v_rate <= 0 OR v_rate > 1 THEN
      RAISE EXCEPTION 'Bracket % rate must be greater than 0 and at most 1', v_position;
    END IF;

    INSERT INTO diocese.progressive_tax_brackets (
      scheme_id, position, minimum_amount, maximum_amount, rate
    ) VALUES (
      v_scheme_id, v_position, v_minimum, v_maximum, v_rate
    );
    v_minimum := v_maximum + 0.01;
  END LOOP;

  RETURN v_scheme_id;
END;
$$;

CREATE OR REPLACE FUNCTION diocese.clone_progressive_tax_scheme(
  p_source_scheme_id uuid,
  p_name text,
  p_effective_month date,
  p_actor_id uuid
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = diocese, public
AS $$
DECLARE
  v_new_id uuid;
BEGIN
  IF p_effective_month IS NULL
     OR p_effective_month <> date_trunc('month', p_effective_month)::date THEN
    RAISE EXCEPTION 'Effective month must be the first day of a month';
  END IF;

  INSERT INTO diocese.progressive_tax_schemes (
    name, effective_month, status, created_by
  )
  SELECT
    COALESCE(NULLIF(btrim(p_name), ''), name || ' Copy'),
    p_effective_month,
    'draft',
    p_actor_id
  FROM diocese.progressive_tax_schemes
  WHERE id = p_source_scheme_id
  RETURNING id INTO v_new_id;

  IF v_new_id IS NULL THEN
    RAISE EXCEPTION 'Source taxation scheme % was not found', p_source_scheme_id;
  END IF;

  INSERT INTO diocese.progressive_tax_brackets (
    scheme_id, position, minimum_amount, maximum_amount, rate
  )
  SELECT v_new_id, position, minimum_amount, maximum_amount, rate
  FROM diocese.progressive_tax_brackets
  WHERE scheme_id = p_source_scheme_id
  ORDER BY position;

  RETURN v_new_id;
END;
$$;

CREATE OR REPLACE FUNCTION diocese.publish_progressive_tax_scheme(
  p_scheme_id uuid,
  p_actor_id uuid
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = diocese, public
AS $$
DECLARE
  v_count integer;
  v_invalid integer;
BEGIN
  PERFORM 1
  FROM diocese.progressive_tax_schemes
  WHERE id = p_scheme_id AND status = 'draft'
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Draft taxation scheme % was not found', p_scheme_id;
  END IF;

  SELECT count(*) INTO v_count
  FROM diocese.progressive_tax_brackets
  WHERE scheme_id = p_scheme_id;
  IF v_count = 0 THEN
    RAISE EXCEPTION 'A taxation scheme cannot be published without brackets';
  END IF;

  SELECT count(*) INTO v_invalid
  FROM (
    SELECT
      position,
      minimum_amount,
      maximum_amount,
      lag(maximum_amount) OVER (ORDER BY position) AS previous_maximum,
      row_number() OVER (ORDER BY position) AS row_number
    FROM diocese.progressive_tax_brackets
    WHERE scheme_id = p_scheme_id
  ) brackets
  WHERE position <> row_number
     OR maximum_amount < minimum_amount
     OR (row_number = 1 AND minimum_amount <> 1.00)
     OR (row_number > 1 AND minimum_amount <> previous_maximum + 0.01);

  IF v_invalid > 0 THEN
    RAISE EXCEPTION 'Taxation brackets must be ordered, gap-free, and non-overlapping';
  END IF;

  UPDATE diocese.progressive_tax_schemes
  SET status = 'published', published_by = p_actor_id, published_at = now()
  WHERE id = p_scheme_id;

  RETURN p_scheme_id;
END;
$$;

INSERT INTO diocese.progressive_tax_schemes (
  name, effective_month, status
) VALUES (
  'Progressive Taxation Scheme 2026',
  DATE '2026-01-01',
  'draft'
)
ON CONFLICT (effective_month) DO NOTHING;

INSERT INTO diocese.progressive_tax_brackets (
  scheme_id, position, minimum_amount, maximum_amount, rate
)
SELECT scheme.id, bracket.position, bracket.minimum_amount, bracket.maximum_amount, bracket.rate
FROM diocese.progressive_tax_schemes scheme
CROSS JOIN (
  VALUES
    (1::smallint,       1.00::numeric,   25000.00::numeric, 0.125::numeric),
    (2::smallint,   25000.01::numeric,   50000.00::numeric, 0.150::numeric),
    (3::smallint,   50000.01::numeric,   80000.00::numeric, 0.175::numeric),
    (4::smallint,   80000.01::numeric,  100000.00::numeric, 0.200::numeric),
    (5::smallint,  100000.01::numeric,  120000.00::numeric, 0.215::numeric),
    (6::smallint,  120000.01::numeric,  125000.00::numeric, 0.225::numeric),
    (7::smallint,  125000.01::numeric,  150000.00::numeric, 0.240::numeric),
    (8::smallint,  150000.01::numeric, 1000000.00::numeric, 0.250::numeric)
) AS bracket(position, minimum_amount, maximum_amount, rate)
WHERE scheme.effective_month = DATE '2026-01-01'
  AND scheme.name = 'Progressive Taxation Scheme 2026'
  AND scheme.status = 'draft'
ON CONFLICT (scheme_id, position) DO NOTHING;

UPDATE diocese.progressive_tax_schemes
SET status = 'published', published_at = now()
WHERE effective_month = DATE '2026-01-01'
  AND name = 'Progressive Taxation Scheme 2026'
  AND status = 'draft';

REVOKE ALL ON diocese.progressive_tax_schemes FROM PUBLIC, anon, authenticated;
REVOKE ALL ON diocese.progressive_tax_brackets FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON
  diocese.progressive_tax_schemes,
  diocese.progressive_tax_brackets
TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA diocese TO service_role;

REVOKE ALL ON FUNCTION diocese.save_progressive_tax_draft(uuid, text, date, jsonb, uuid)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION diocese.clone_progressive_tax_scheme(uuid, text, date, uuid)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION diocese.publish_progressive_tax_scheme(uuid, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION diocese.save_progressive_tax_draft(uuid, text, date, jsonb, uuid)
  TO service_role;
GRANT EXECUTE ON FUNCTION diocese.clone_progressive_tax_scheme(uuid, text, date, uuid)
  TO service_role;
GRANT EXECUTE ON FUNCTION diocese.publish_progressive_tax_scheme(uuid, uuid)
  TO service_role;

COMMIT;
